spring:
  application:
    name: '@project.name@'
  profiles:
    active: local
  jta:
    enabled: false
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.training.samples.spring.shop: INFO