server:
  port: 8080
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers
logging:
  level:
    org.hibernate.SQL: DEBUG
spring:
  shop:
    showItems:
      url: http://localhost:8081/api/items